// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDJzrzqXzNlcD8tZs0jPDMJf3dVMoVPxw',
    appId: '1:797589268443:web:a26d0fe9035adfa2c429fe',
    messagingSenderId: '797589268443',
    projectId: 'fasum-81289',
    authDomain: 'fasum-81289.firebaseapp.com',
    databaseURL: 'https://fasum-81289-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-81289.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAyulifDbRgBUeLl6uk424UD9T7MoCo0',
    appId: '1:797589268443:android:717f05cfdad4b2c0c429fe',
    messagingSenderId: '797589268443',
    projectId: 'fasum-81289',
    databaseURL: 'https://fasum-81289-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-81289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUmsxWHmOdEkFD7ulBiJgb9tBa1WcsnvE',
    appId: '1:797589268443:ios:df60928fa39002a0c429fe',
    messagingSenderId: '797589268443',
    projectId: 'fasum-81289',
    databaseURL: 'https://fasum-81289-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-81289.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUmsxWHmOdEkFD7ulBiJgb9tBa1WcsnvE',
    appId: '1:797589268443:ios:df60928fa39002a0c429fe',
    messagingSenderId: '797589268443',
    projectId: 'fasum-81289',
    databaseURL: 'https://fasum-81289-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-81289.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDJzrzqXzNlcD8tZs0jPDMJf3dVMoVPxw',
    appId: '1:797589268443:web:e7fc7affdfdff8c0c429fe',
    messagingSenderId: '797589268443',
    projectId: 'fasum-81289',
    authDomain: 'fasum-81289.firebaseapp.com',
    databaseURL: 'https://fasum-81289-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-81289.firebasestorage.app',
  );

}